version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    container_name: app_frontend
    networks:
      - app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - app
    container_name: app_backend
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=userpass
      - MYSQL_ROOT_PASSWORD=rootpass
    container_name: app_db
    ports:
      - "3306:3306"
    networks:
      - app
volumes:
  mysql:
networks:
  app:
    driver: bridge
